apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smart-crawler
    kind: tiktok-crawler
    platform: tiktok
    type: search-post
  name: sc-tiktok-crawler-search-post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-crawler
      kind: tiktok-crawler
      platform: tiktok
      type: search-post
  template:
    metadata:
      labels:
        app: smart-crawler
        kind: tiktok-crawler
        platform: tiktok
        type: search-post
    spec:
      hostAliases:
        - ip: "192.168.24.201"
          hostnames:
            - "kafka01.production.bt"
        - ip: "192.168.24.202"
          hostnames:
            - "kafka02.production.bt"
      containers:
      - name: sc-tiktok-crawler-search-post
        image: 192.168.202.50/clipper/smart-crawler/tiktok-crawler
        args:
          - 'crawler'
          - '--mode=full'
          - '-d=kafka'
          - '-o=tiktok.posts.raw'
          - '--bootstrap-servers=kafka01.production.bt:9092,kafka02.production.bt:9092'
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /app/../config.yaml
          name: config
          subPath: config.yaml
      volumes:
      - configMap:
          name: config-tiktok-crawler
        name: config
